# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(max_length=100)),
                ('officeLoc', models.TextField(max_length=100)),
                ('slackName', models.TextField(max_length=50)),
                ('hireDate', models.DateField(blank=True, null=True)),
                ('phoneNum', models.TextField(max_length=25)),
                ('jobTitle', models.TextField(max_length=200)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
