# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDir', '0003_auto_20170317_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./static/kb/'),
        ),
    ]
