# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDir', '0004_auto_20170317_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./kb/static/images/'),
        ),
    ]
