# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingManuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmName', models.CharField(max_length=200)),
                ('tmContent', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
