# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullyUserMedals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medalName', models.CharField(max_length=100)),
                ('fullyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.FullyUser')),
            ],
        ),
    ]
