# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_fullyusermedals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullyusermedals',
            name='fullyUser',
        ),
        migrations.DeleteModel(
            name='FullyUserMedals',
        ),
    ]
