# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0003_auto_20170315_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullyBikeTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeDate', models.DateField()),
                ('fullyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.FullyUser')),
            ],
        ),
    ]
